//jshint esversion: 9
export const ADD_NEW_ELEMENT = "ADD_NEW_ELEMENT";

export const UPDATE_ELEMENT_FIELDS = "UPDATE_ELEMENTS_FIELDS";

export const REMOVE_ELEMENT = "REMOVE_ELEMENT";

export const REMOVE_ALL_ELEMENT = "REMOVE_ALL_ELEMENT";
